name: Test and Release

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight UTC
  workflow_dispatch:      # Allow manual triggers

permissions:
  contents: write

jobs:
  style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install LLVM 18
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
      - run: cargo build --release
      - run: cargo test --release
      
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-bin
          path: target/release/book

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Get Weekly Tag
        run: echo "DATE_TAG=weekly-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Download Built Binary
        uses: actions/download-artifact@v4
        with:
          name: book-bin
          path: release

      - name: Create Release
        run: |
          gh release create ${{ env.DATE_TAG }} \
            --title "Weekly Release ${{ env.DATE_TAG }}" \
            --notes "Automated weekly build" \
            --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Binary Assets
        run: |
          cd release
          zip -r book-${{ env.DATE_TAG }}.zip book
          gh release upload ${{ env.DATE_TAG }} \
            book \
            book-${{ env.DATE_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
